version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VUE_APP_API_BASE_URL: http://localhost:8090
      VUE_APP_AUTH_METHOD: saml
    ports:
      - '9999:8080'
    container_name: office-frontend
    volumes:
      - .:/app
